### ISSUE TITLE
Notification Closes too Soon Upon Inertia.js Navigation

### ISSUE THREAD

**Issue by coolsam726** [emmanuelsw/notiwind#2]
I tried the library with Inertia.js with Laravel, and here is what is expected vs what happens upon Inertia Navigation.

## Expected (This works with [vue3-vt-notifications](https://github.com/killmenot/vue3-vt-notifications))
![notifications-expected-with-inertia](https://user-images.githubusercontent.com/5610289/128004791-e65922e8-0525-498d-bbb4-9b905d269118.gif)

## Found (Issue with notiwind)
![notifications-failing-with-inertiajs](https://user-images.githubusercontent.com/5610289/128004826-168ccda6-e257-41ba-bbd7-6d2f9bfeeb03.gif)

**Comment by emmanuelsw** [comment]
Can you provide a reproduction repo?
I am currently using the library in an application built with Rails + Inertia and it works perfectly.

I also tested it in a fresh Rails + Inertia application and it works well:
![test-notiwind-inertia](https://user-images.githubusercontent.com/8741580/128426604-a13996f1-ee03-40af-bf83-9a8431f32c51.gif)

**Comment by emmanuelsw** [comment]
I'm closing this one due to inactivity, feel free to reopen it whenever you want!
