### ISSUE TITLE
Is there any way to use it in vue 2 version?

### ISSUE THREAD

**Issue by chl3188** [emmanuelsw/notiwind#4]
Hello
It's good to find such a pretty notification.
The vue version of the project I make is 2 versions, so it is not available.
Is there any way to use it in the vue2 version?

**Comment by emmanuelsw** [comment]
Hello!
You can use this library https://github.com/sansil/vt-notifications. 
Notiwind is a fork of that library so it's basically the same but only works with Vue 2.
