### ISSUE TITLE
maxNotifications to be applied immediately

### ISSUE THREAD

**Issue by Tamas-hi** [emmanuelsw/notiwind#40]
Hi there,

I really enjoy this library, however I have an issue with the current way the maxNotifications prop works.
If I set it to one, I would like only one notification to pop up. 

Currently, many more appear for a moment and then they fade away leaving the only one behind. Is there anyway we can make maxNotifications to completely prevent adding additional notifications even for a split second?

Thank you!

**Comment by emmanuelsw** [comment]
Fixed #41
